theme: minima
title: My incredible blog
author: Qnomon
email: eric_olv@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about game development and python

# social links
twitter_username: qnomon # DO NOT include the @ character, or else the build will fail!
github_username:  qnomon # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
